services:
  geoparser:
    # Use pre-built image from Docker Hub
    image: realjensen/geoparser-api:latest
    ports:
      - "${PORT:-5000}:5000"
    env_file:
      - .env
    volumes:
      # Models and data directories - ensure models are downloaded to these paths
      - ./models:/app/models
      - ./data:/app/data
      # Optional: logs directory for storing logs
      - ./logs:/app/logs
    restart: unless-stopped
    entrypoint: ["/app/entrypoint.sh"]
    command: >
      gunicorn app.api:app
      --bind 0.0.0.0:5000
      --workers ${WORKERS:-2}
      --timeout ${WORKER_TIMEOUT:-600}
      --worker-class ${WORKER_CLASS:-sync}
      --max-requests ${MAX_REQUESTS:-1000}
      --max-requests-jitter ${MAX_REQUESTS_JITTER:-100}
      --access-logfile -
      --error-logfile -
    # GPU configuration (comment out if not using GPU)
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 600s  # Allow 10 minutes for models to load
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-12G}
          cpus: '${CPU_LIMIT:-2.0}'
        reservations:
          memory: ${MEMORY_RESERVATION:-6G}
          cpus: '${CPU_RESERVATION:-1.0}'
        # Uncomment for GPU support
        # reservations:
        #   devices:
        #     - driver: nvidia
        #       count: 1
        #       capabilities: [gpu]
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-10m}"
        max-file: "${LOG_MAX_FILE:-5}"
    networks:
      - geoparser_network

networks:
  geoparser_network:
    driver: bridge 